routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* ROUTES FRONT */
Route::get('/', 'HomeController@index')->name('index');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/portfolio', 'HomeController@portfolio')->name('portfolio');
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/contact', 'ContactController@sendMail')->name('contact.send');

/* ROUTES ADMIN */
Route::get('/admin', 'AdminLoginController@admin')->name('admin');
Route::post('/admin', 'AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'AdminLoginController@logout')->name('admin.logout');
Route::get('/admin/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
Route::get('/admin/settings', 'SettingController@index')->name('settings.index');
Route::post('/admin/settings', 'SettingController@edit')->name('settings.edit');
/* ROUTES RESOURCE ADMIN */
Route::resource('admin/skills', 'SkillController');
Route::resource('admin/projects', 'ProjectController');
Route::resource('admin/categories', 'CategoryController');

app/Project.php
<?php

namespace App;

use App\src\Traits\Project\Project as ProjectTrait;
use App\src\Traits\Project\Project\ProjectScopes;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Project extends Model
{
    use ProjectTrait, ProjectScopes;

    /**
     * @var bool
     */
    public bool $timestamps = true;
    /**
     * @var array
     */
    protected array $guarded = [];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @param object $projects
     * @return array
     */
    public function setCountProjectByYear(object $projects): array
    {
        $dataProjects = [];
        foreach ($projects as $project) {
            $date = Carbon::parse($project->start_project)->format('Y');
            $dataProjects[$date][] = $project;
        }
        // Count the projects by Years !
        $data = [];
        foreach ($dataProjects as $dataProject) {
            $data[] = count($dataProject);
        }
        return $data;
    }

    /**
     * @param object $projects
     * @return array
     */
    public function setYearsData(object $projects): array
    {
        $dataYears = [];
        foreach ($projects as $project) {
            $year = Carbon::parse($project->start_project)->format('Y');
            if (!in_array($year, $dataYears)) {
                $dataYears[] = $year;
            }
        }
        return $dataYears;
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Project;
use App\Skill;
use App\SkillProject;
use App\src\Helpers\DateHelpers;
use App\src\Helpers\Image;
use App\src\Helpers\Regex;
use App\src\Messages\Message;
use App\src\Traits\Project\ProjectImage;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\View\View;

class ProjectController extends Controller
{

    use ProjectImage;

    /**
     * @var DateHelpers
     */
    private DateHelpers $dateHelper;
    /**
     * @var Message
     */
    private Message $message;
    /**
     * @var Image
     */
    private Image $imageBuild;
    /**
     * @var SkillProject
     */
    private SkillProject $skillProject;

    /**
     * ProjectController constructor.
     */
    public function __construct() {
        $this->dateHelper = new DateHelpers();
        $this->message = new Message();
        $this->imageBuild = new Image();
        $this->skillProject = new SkillProject();
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        $projects = Project::paginate(10);
        return view('admin.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        $project = null;
        $categories = Category::all();

        $skillsBack = Skill::BackOrFront()->get();
        $skillsFront = Skill::BackOrFront('front_end')->get();
        return view('admin.projects.create', compact('project', 'categories', 'skillsBack', 'skillsFront'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $credentials = $request->except('back_end', 'front_end');
        $validator = $this->setValidator($request->all());
        if ($validator->fails()) {
            return redirect()
                ->route('projects.create')
                ->withErrors($validator->errors())
                ->with('danger', 'An error has been occurred when to creating project !');
        }
        // Validate data request
        // Verify If end date project is more recent || start date project and end fate project are identical
        if ($this->dateHelper->tooRecentEndDate($credentials['start_project'], $credentials['end_project'])) {
            return redirect()
                ->route('projects.create')
                ->with('danger', 'The end project date don\'t must be more recent than the start project date !');
        }
        if ($this->dateHelper->identicalDate($credentials['start_project'], $credentials['end_project'])) {
            return redirect()
                ->route('projects.create')
                ->with('danger', 'The end project date don\'t must be identical than the start project date !');
        }
        $image = $this->setImage($request);
        if ($this->error()) {
            return $this->setError();
        }
        $credentials['slug'] = Str::slug($credentials['title']);
        $credentials['image'] = $image;
        Project::create($credentials);

        $credentials = $request->only('back_end', 'front_end');
        $this->skillProject->setSkillsToProject($credentials);
        if ($this->skillProject->error()) {
            return $this->skillProject->setError();
        }
        return redirect()->route('admin.dashboard')->with('success', 'You are created your project with success !');
    }

    /**
     * Display the specified resource.
     *
     * @param Project $project
     * @return Application|Factory|Response|View
     */
    public function show(Project $project)
    {
        $skillsBackEnd = SkillProject::joinSkills()
            ->GetByProjectID('project_skill_project.project_id', $project->id)
            ->GetByBackOrFront('skills.back_or_front', 'back_end')
            ->get();
        $skillsFrontEnd = SkillProject::joinSkills()
            ->GetByProjectID('project_skill_project.project_id', $project->id)
            ->GetByBackOrFront('skills.back_or_front', 'front_end')
            ->get();
        $project = Project::findOrFail($project->id);
        return \view('projects.show', compact('project', 'skillsBackEnd', 'skillsFrontEnd'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Project $project
     * @return Application|Factory|Response|View
     */
    public function edit(Project $project)
    {
        $project = Project::findOrfail($project->id);
        $categories = Category::all();

        $skillsBack = Skill::BackOrFront()->get();
        $skillsFront = Skill::BackOrFront('front_end')->get();
        return view('admin.projects.edit', compact('project', 'categories', 'skillsBack', 'skillsFront'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Project $project
     * @return RedirectResponse
     */
    public function update(Request $request, Project $project): RedirectResponse
    {
        $credentials = $request->except('back_end', 'front_end');
        $validator = $this->setValidator($request->all());
        if ($validator->fails()) {
            return redirect()
                ->route('projects.edit', [$project->id])
                ->withErrors($validator->errors())
                ->with('danger', 'An error has been occurred when to edited project !');
        }
        // Validate data request
        // Verify If end date project is more recent || start date project and end fate project are identical
        if ($this->dateHelper->tooRecentEndDate($credentials['start_project'], $credentials['end_project'])) {
            return redirect()
                ->route('projects.create')
                ->with('danger', 'The end project date don\'t must be more recent than the start project date !');
        }
        if ($this->dateHelper->identicalDate($credentials['start_project'], $credentials['end_project'])) {
            return redirect()
                ->route('projects.create')
                ->with('danger', 'The end project date don\'t must be identical than the start project date !');
        }
        $credentials['slug'] = Str::slug($credentials['title']);
        $project->update($credentials);

        $credentials = $request->only('back_end', 'front_end');
        $this->skillProject->setSkillsToProject($credentials);
        if ($this->skillProject->error()) {
            return $this->skillProject->setError();
        }
        return redirect()->route('admin.dashboard')->with('success', 'You are edited your project with success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Project|null $project
     * @return RedirectResponse
     */
    public function destroy(?Project $project): RedirectResponse
    {
        $project = Project::findOrFail($project->id);
        $project->delete();
        return $this->message->renderSuccess('projects.index', [], 'You are deleted your project with success !');
    }

    /**
     * @param array $credentials
     * @return \Illuminate\Contracts\Validation\Validator
     */
    private function setValidator(array $credentials): \Illuminate\Contracts\Validation\Validator
    {
        $regex =  Regex::Url();
        return Validator::make($credentials, [
            'title' => 'required|min:5|max:250',
            'link_web' => 'required|regex:' . $regex,
            'content' => 'required|min:10',
            'conclusion' => 'required|min:10',
            'category_id' => 'required|integer',
            'start_project' => 'required|date',
            'end_project' => 'required|date',
            'back_end' => 'required|array|min:1',
            'front_end' => 'required|array|min:1',
            'front_end.*' => 'required|string|distinct|min:2',
            'back_end.*' => 'required|string|distinct|min:2',
            'image' => 'file'
        ]);
    }
}

resources/views/admin/projects/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Create project</h4>
        </div>
    </div>
    <div id="form-create-project">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form project create</h4>
                <p class="card-description">
                    Here, you cab create your project !
                </p>
                @include('admin.projects.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/projects/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Edit project</h4>
        </div>
    </div>
    <div id="form-create-project">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form project edit</h4>
                <p class="card-description">
                    Here, you cab edit your project !
                </p>
                @include('admin.projects.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/projects/form.blade.php
<form action="{{ $project !== null ? route('projects.update', [$project]) : route('projects.store') }}" method="POST"
      id="form-project" enctype="multipart/form-data">
    @if ($project)
        @method('PUT')
    @endif
    @csrf
    <fieldset>
        <div class="form-group row">
            <div class="col-md-6">
                <label for="title">Title</label>
                <input id="title" type="text" name="title" class="form-control"
                       value="{{$project !== null ? $project->title : null }}" placeholder="Your project title...">
            </div>
            <div class="col-md-6">
                <label for="category">Cateory</label>
                <select name="category_id" id="category" class="form-control">
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-6">
                <label for="start_project">Start Date Project</label>
                <input type="date" name="start_project" id="start_project" class="form-control"
                       value="{{ $project !== null ? $project->start_project : null }}">
            </div>
            <div class="col-md-6">
                <label for="end_project">End Date Project</label>
                <input type="date" name="end_project" id="end_project" class="form-control"
                       value="{{ $project !== null ? $project->end_project : null }}">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-6">
                <label for="back_end">Technologie Back End</label>
                <select name="back_end[]" id="back_end" class="form-control" multiple>
                    @foreach($skillsBack as $skillBack)
                        <option value="{{ $skillBack->name }}">{{ $skillBack->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-6">
                <label for="front_end">Technologie Front End</label>
                <select name="front_end[]" id="front_end" class="form-control" multiple>
                    @foreach($skillsFront as $skillFront)
                        <option value="{{ $skillFront->name }}">{{ $skillFront->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="link_web">Link to Web</label>
            <input type="text" name="link_web" id="link_web" class="form-control" placeholder="Link to web...">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea name="content" id="content" class="form-control" cols="30"
                      placeholder="Your content..."
                      rows="10">{{ $project !== null ? $project->content : null }}</textarea>
        </div>
        <div class="form-group">
            <label for="conclusion">Conclusion</label>
            <textarea name="conclusion" id="conclusion" class="form-control" cols="30"
                      placeholder="Your content..."
                      rows="10">{{ $project !== null ? $project->conclusion : null }}</textarea>
        </div>
        <div class="form-group">
            <label for="image">Image</label>
            <input type="file" name="image" id="image" class="file-upload-default">
            <div class="input-group col-xs-12">
                <input type="text" class="form-control file-upload-info" placeholder="Upload Image" disabled>
                <span class="input-group-append">
                    <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                </span>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </fieldset>
</form>

@section('extra-js')
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{{ asset('js/admin/lib/FileUpload.js') }}" type="module" defer></script>
@endsection

resources/views/admin/projects/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Projects</h4>
        </div>
    </div>
    @include('admin.projects.projects-table')
@endsection

resources/views/admin/projects/projects-table.blade.php
<div id="projects-table" class="stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-baseline mb-2">
                <h6 class="card-title mb-0">Projects</h6>
            </div>
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                    <tr>
                        <th class="pt-0">#</th>
                        <th class="pt-0">Project Name</th>
                        <th class="pt-0">Project Slug</th>
                        <th class="pt-0">Link Web</th>
                        <th class="pt-0">Content</th>
                        <th class="pt-0">Start Date</th>
                        <th class="pt-0">End Date</th>
                        <th class="pt-0">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($projects as $project)
                            <tr>
                                <td>{{ $project->id  }}</td>
                                <td>{{ $project->title }}</td>
                                <td>{{ $project->slug }}</td>
                                <td>{{ $project->link_web }}</td>
                                <td>{{ $project->getContent() }}</td>
                                <td>{{ $project->start_project }}</td>
                                <td>{{ $project->end_project }}</td>
                                <td>
                                    <a href="{{ route('projects.edit', [$project->id]) }}" type="button" class="btn btn-outline-success">Edit</a>
                                    <button type="button" class="btn btn-outline-danger" id="delete-btn">Delete</button>
                                    <form action="{{ route('projects.destroy', [$project]) }}" method="POST" id="delete-form">
                                        @method('DELETE')
                                        @csrf
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>