routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* ROUTES FRONT */
Route::get('/', 'HomeController@index')->name('index');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/portfolio', 'HomeController@portfolio')->name('portfolio');
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/contact', 'ContactController@sendMail')->name('contact.send');

/* ROUTES ADMIN */
Route::get('/admin', 'AdminLoginController@admin')->name('admin');
Route::post('/admin', 'AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'AdminLoginController@logout')->name('admin.logout');
Route::get('/admin/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
Route::get('/admin/settings', 'SettingController@index')->name('settings.index');
Route::post('/admin/settings', 'SettingController@edit')->name('settings.edit');
/* ROUTES RESOURCE ADMIN */
Route::resource('admin/skills', 'SkillController');
Route::resource('admin/projects', 'ProjectController');
Route::resource('admin/categories', 'CategoryController');

app/Skill.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    public bool $timestamps = true;
    /**
     * @var array|string[]
     */
    protected array $fillable = ['name', 'link', 'percentage', 'type', 'back_or_front'];

    /**
     * @param string $value
     * @return string
     */
    public function getCreatedAtAttribute(string $value): string
    {
        return Carbon::create($value)->format('Y-m-d');
    }

    /**
     * @param object $skills
     * @return array
     */
    public function setDataSkillsPercentage(object $skills): array
    {
        $newData = [];
        foreach ($skills as $skill) {
            $newData[] = floatval($skill->percentage);
        }
        return $newData;
    }

    /**
     * @param object $skills
     * @return array
     */
    public function setDataSkillsTechno(object $skills): array
    {
        $newData = [];
        foreach ($skills as $skill) {
            $newData[] = $skill->name ?: 'Techno Undefined';
        }
        return $newData;
    }

    /**
     * @param $query
     * @param string $type
     * @return mixed
     */
    public function scopeByType($query, string $type)
    {
        return $query->where('type', $type);
    }

    /**
     * @param $query
     * @param string $backOrFront
     * @return mixed
     */
    public function scopeBackOrFront($query, string $backOrFront = 'back_end')
    {
        return $query->where('back_or_front', $backOrFront);
    }

    /**
     * @param $query
     * @param string $name
     * @return mixed
     */
    public function scopeGetByName($query, string $name)
    {
        return $query->where('name', $name);
    }
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Skill;
use App\src\Helpers\Regex;
use App\src\Traits\SkillControllerTrait;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class SkillController extends Controller
{

    use SkillControllerTrait;

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $skills = Skill::paginate(10);
        return view('admin.skills.index', compact('skills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $skill = null;
        return view('admin.skills.create', compact('skill'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $credentials = $request->all();
        $validator = $this->setValidator($credentials);
        if ($validator->fails()) {
            return $this->message->renderError('skills.create', [], 'An error has been occurred when to creating skill !', $validator);
        }
        if ($this->checkDataType($credentials)) {
            return $this->setError('The field type must contain "techno" or "language" !');
        }
        if ($this->checkDataBackOrFront($credentials)) {
            return $this->setError('The field back or front must contain "back_end" or "front_end" !');
        }
        Skill::create($credentials);
        return redirect()->route('skills.index')->with('success', 'You are created your skill with success !');
    }

    /**
     * @param array $credentials
     * @return \Illuminate\Contracts\Validation\Validator
     */
    private function setValidator(array $credentials): \Illuminate\Contracts\Validation\Validator
    {
        $regex = Regex::Url();
        return Validator::make($credentials, [
            'name' => 'required|max:25',
            'link' => 'required|regex:' . $regex,
            'percentage' => 'required|integer',
            'type' => 'required|string',
            'back_or_front' => 'required|string'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param Skill $skill
     * @return Response
     */
    public function show(Skill $skill)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Skill $skill
     * @return Application|Factory|View
     */
    public function edit(Skill $skill)
    {
        $skill = Skill::find((integer)$skill->id);
        return view('admin.skills.edit', compact('skill'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Skill $skill
     * @return RedirectResponse
     */
    public function update(Request $request, Skill $skill): RedirectResponse
    {
        $credentials = $request->all();
        $validator = $this->setValidator($credentials);
        if ($validator->fails()) {
            return redirect()
                ->route('skills.edit', [$skill])
                ->withErrors($validator->errors())
                ->with('danger', 'An error has been occurred when to editing skill !');
        }
        if ($this->checkDataType($credentials)) {
            return $this->setError('The field type must contain "techno" or "language" !');
        }
        if ($this->checkDataBackOrFront($credentials)) {
            return $this->setError('The field back or front must contain "back_end" or "front_end" !');
        }
        $skill->update($credentials);
        return redirect()->route('skills.index')->with('success', 'You are updated your skill with success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Skill $skill
     * @return RedirectResponse
     */
    public function destroy(Skill $skill): RedirectResponse
    {
        $skill = Skill::findOrFail($skill->id);
        $skill->delete();
        return $this->message->renderSuccess('skills.index', [], 'You are deleted your skill with success !');
    }
}

resources/views/admin/skills/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Create skill</h4>
        </div>
    </div>
    <div id="form-skill-create" class="grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form skill create</h4>
                <p class="card-description">
                    Here, you can create your skill !
                </p>
                @include('admin.skills.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/skills/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Edit skill "{{ $skill->name }}"</h4>
        </div>
    </div>
    <div id="form-skill-edit" class="grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form skill edit</h4>
                <p class="card-description">
                    Here, you are edit your skill "{{ $skill->name }}" !
                </p>
                @include('admin.skills.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/skills/form.blade.php
<form action="{{ $skill !== null ? route('skills.update', [$skill]) : route('skills.store') }}" method="POST" id="form-skill">
    @if ($skill)
        @method('PUT')
    @endif
    @csrf
    <fieldset>
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name" type="text" name="name" class="form-control" value="{{$skill !== null ? $skill->name : null }}" placeholder="Your skill name...">
        </div>
        <div class="form-group">
            <label for="link">Link</label>
            <input id="link" type="text" name="link" class="form-control" value="{{$skill !== null ? $skill->link : null }}" placeholder="Your link...">
        </div>
        <div class="form-group">
            <label for="percentage">Percentage</label>
            <input id="percentage" type="number" name="percentage" class="form-control" value="{{ $skill !== null ? $skill->percentage : 50 }}">
        </div>
        <div class="form-group">
            <label for="type">Type</label>
            <select name="type" id="type" class="form-control">
                <option value="language" {{ $skill !== null && $skill->type === 'language' ? 'selected' : null }}>Language</option>
                <option value="techno" {{ $skill !== null && $skill->type === 'techno' ? 'selected' : null }}>Techno</option>
            </select>
        </div>
        <div class="form-group">
            <label for="back_or_front">Back Or Front ?</label>
            <select name="back_or_front" id="back_or_front" class="form-control">
                <option value="back_end" {{ $skill !== null && $skill->back_or_front === 'back_end' ? 'selected' : null }}>Back End</option>
                <option value="front_end" {{ $skill !== null && $skill->back_or_front === 'front_end' ? 'selected' : null }}>Front End</option>
            </select>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </fieldset>
</form>

resources/views/admin/skills/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Skills</h4>
        </div>
    </div>
    @include('admin.skills.skills-table')
@endsection

resources/views/admin/skills/skills-table.blade.php
<div id="skills-table" class="stretch-card pt-3">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-baseline mb-2">
                <h6 class="card-title mb-0">Skills</h6>
            </div>
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                    <tr>
                        <th class="pt-0">#</th>
                        <th class="pt-0">Skill Name</th>
                        <th class="pt-0">Link</th>
                        <th class="pt-0">Percentage</th>
                        <th class="pt-0">Type</th>
                        <th class="pt-0">Back or Front ?</th>
                        <th class="pt-0">Date</th>
                        <th class="pt-0">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($skills as $skill)
                            <tr>
                                <td>{{ $skill->id }}</td>
                                <td>{{ $skill->name }}</td>
                                <td>{{ $skill->link }}</td>
                                <td>{{ $skill->percentage }}%</td>
                                <td>{{ $skill->type }}</td>
                                <td>{{ $skill->back_or_front }}</td>
                                <td>{{ $skill->created_at }}</td>
                                <td>
                                    <a href="{{ route('skills.edit', [$skill]) }}" type="button" class="btn btn-outline-success">Edit</a>
                                    <button type="button" class="btn btn-outline-danger" id="delete-btn">Delete</button>
                                    <form action="{{ route('skills.destroy', [$skill]) }}" method="POST" id="delete-form">
                                        @method('DELETE')
                                        @csrf
                                    </form>
                                </td>
                            </tr
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>