routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* ROUTES FRONT */
Route::get('/', 'HomeController@index')->name('index');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/portfolio', 'HomeController@portfolio')->name('portfolio');
Route::get('/contact', 'ContactController@contact')->name('contact');
Route::post('/contact', 'ContactController@sendMail')->name('contact.send');

/* ROUTES ADMIN */
Route::get('/admin', 'AdminLoginController@admin')->name('admin');
Route::post('/admin', 'AdminLoginController@login')->name('admin.login');
Route::post('/admin/logout', 'AdminLoginController@logout')->name('admin.logout');
Route::get('/admin/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
Route::get('/admin/settings', 'SettingController@index')->name('settings.index');
Route::post('/admin/settings', 'SettingController@edit')->name('settings.edit');
/* ROUTES RESOURCE ADMIN */
Route::resource('admin/skills', 'SkillController');
Route::resource('admin/projects', 'ProjectController');
Route::resource('admin/categories', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    /**
     * @var array
     */
    protected array $guarded = [];

    /**
     * @var bool
     */
    public bool $timestamps = true;

    /**
     * @return HasMany
     */
    public function project(): HasMany
    {
        return $this->hasMany(Project::class);
    }

    /**
     * @param $query
     * @param string $slug
     * @return mixed
     */
    public function scopeGetBySlug($query, string $slug)
    {
        return $query->where('slug', $slug)->get();
    }
}

app/Skill.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    public bool $timestamps = true;
    /**
     * @var array|string[]
     */
    protected array $fillable = ['name', 'link', 'percentage', 'type', 'back_or_front'];

    /**
     * @param string $value
     * @return string
     */
    public function getCreatedAtAttribute(string $value): string
    {
        return Carbon::create($value)->format('Y-m-d');
    }

    /**
     * @param object $skills
     * @return array
     */
    public function setDataSkillsPercentage(object $skills): array
    {
        $newData = [];
        foreach ($skills as $skill) {
            $newData[] = floatval($skill->percentage);
        }
        return $newData;
    }

    /**
     * @param object $skills
     * @return array
     */
    public function setDataSkillsTechno(object $skills): array
    {
        $newData = [];
        foreach ($skills as $skill) {
            $newData[] = $skill->name ?: 'Techno Undefined';
        }
        return $newData;
    }

    /**
     * @param $query
     * @param string $type
     * @return mixed
     */
    public function scopeByType($query, string $type)
    {
        return $query->where('type', $type);
    }

    /**
     * @param $query
     * @param string $backOrFront
     * @return mixed
     */
    public function scopeBackOrFront($query, string $backOrFront = 'back_end')
    {
        return $query->where('back_or_front', $backOrFront);
    }

    /**
     * @param $query
     * @param string $name
     * @return mixed
     */
    public function scopeGetByName($query, string $name)
    {
        return $query->where('name', $name);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\src\Messages\Message;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\View\View;

class CategoryController extends Controller
{

    /**
     * @var Message
     */
    private Message $message;

    public function __construct()
    {
        $this->message = new Message();
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        $category = null;
        return view('admin.categories.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $credentials = $request->all();
        $validator = Validator::make($credentials, [
            'name' => 'required|min:2|max:60',
            'content' => 'required|min:10'
        ]);
        if ($validator->fails()) {
            return redirect()
                ->route('categories.create')
                ->withErrors($validator->errors())
                ->with('danger', 'An error has been occurred when to creating project !');
        }
        $credentials['slug'] = Str::slug($credentials['name']);
        Category::create($credentials);
        return redirect()->route('categories.index')->with('success', 'You are created your category with success !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function edit(int $id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, int $id): RedirectResponse
    {
        $credentials = $request->all();
        $validator = $this->setValidator($credentials);
        if ($validator->fails()) {
            return redirect()
                ->route('categories.edit', [$id])
                ->withErrors($validator->errors())
                ->with('danger', 'An error has been occurred when to editing project !');
        }
        $credentials['slug'] = Str::slug($credentials['name']);
        $category = Category::findOrFail($id);
        $category->update($credentials);
        return redirect()->route('categories.index')->with('success', 'You are edited your category with success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return $this->message->renderSuccess('categories.index', [], 'You are deleted your category with success !');
    }

    /**
     * @param array $credentials
     * @return \Illuminate\Contracts\Validation\Validator
     */
    private function setValidator(array $credentials): \Illuminate\Contracts\Validation\Validator
    {
        return Validator::make($credentials, [
            'name' => 'required|min:2|max:60',
            'content' => 'required|min:10'
        ]);
    }
}

resources/views/admin/categories/categories-table.blade.php
<div id="categories-table" class="stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-baseline mb-2">
                <h6 class="card-title mb-0">Categories</h6>
            </div>
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                    <tr>
                        <th class="pt-0">#</th>
                        <th class="pt-0">Category Name</th>
                        <th class="pt-0">Category Slug</th>
                        <th class="pt-0">Category Content</th>
                        <th class="pt-0">Date</th>
                        <th class="pt-0">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{ $category->id  }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->slug }}</td>
                            <td>{{ $category->content }}</td>
                            <td>{{ $category->created_at }}</td>
                            <td>
                                <a href="{{ route('categories.edit', [$category->id]) }}" type="button" class="btn btn-outline-success">Edit</a>
                                <button type="button" class="btn btn-outline-danger" id="delete-btn">Delete</button>
                                <form action="{{ route('categories.destroy', [$category]) }}" method="POST" id="delete-form">
                                    @method('DELETE')
                                    @csrf
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Create Category</h4>
        </div>
    </div>
    <div id="form-create-category">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form category create</h4>
                <p class="card-description">
                    Here, you cab create your category for the projects !
                </p>
                @include('admin.categories.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Edit Category "{{ $category->name }}"</h4>
        </div>
    </div>
    <div id="form-create-category">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Form category edit</h4>
                <p class="card-description">
                    Here, you can edited your category for the projects !
                </p>
                @include('admin.categories.form')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/form.blade.php
<form action="{{ $category !== null ? route('categories.update', [$category]) : route('categories.store') }}"
      method="POST"
      id="form-project">
    @if ($category)
        @method('PUT')
    @endif
    @csrf
    <fieldset>
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name" type="text" name="name" class="form-control"
                   value="{{$category !== null ? $category->name : null }}" placeholder="Your category name...">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea name="content" id="content" class="form-control" cols="30"
                      rows="10"
                      placeholder="Your category content...">{{ $category !== null ? $category->content : null }}</textarea>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </fieldset>
</form>

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Categories</h4>
        </div>
    </div>
    @include('admin.categories.categories-table')
@endsection